// Master resource price database (USD base) + AHSP-style construction items.
// Prices are editable per project; the geometry stays independent of prices.

export const DEFAULT_RESOURCES = [
  // Materials
  { id: "cement", name: "Cement (50kg bag)", type: "material", unit: "bag", price: 7 },
  { id: "sand", name: "Sand", type: "material", unit: "m3", price: 25 },
  { id: "gravel", name: "Gravel", type: "material", unit: "m3", price: 30 },
  { id: "brick", name: "Brick", type: "material", unit: "pcs", price: 0.15 },
  { id: "rebar", name: "Reinforcement Steel", type: "material", unit: "kg", price: 0.9 },
  { id: "ceramic_tile", name: "Ceramic Tile", type: "material", unit: "m2", price: 12 },
  { id: "paint", name: "Paint", type: "material", unit: "liter", price: 6 },
  { id: "gypsum_board", name: "Gypsum Board", type: "material", unit: "m2", price: 8 },
  { id: "roof_tile", name: "Roof Tile", type: "material", unit: "m2", price: 15 },
  { id: "timber", name: "Timber", type: "material", unit: "m3", price: 300 },
  { id: "door_leaf", name: "Door Unit", type: "material", unit: "unit", price: 120 },
  { id: "window_unit", name: "Window Unit", type: "material", unit: "unit", price: 90 },
  { id: "pipe_pvc", name: "PVC Pipe", type: "material", unit: "m", price: 3 },
  { id: "wire", name: "Electrical Wire", type: "material", unit: "m", price: 0.8 },
  { id: "lamp_fixture", name: "Lamp Fixture", type: "material", unit: "unit", price: 15 },
  { id: "switch_unit", name: "Switch", type: "material", unit: "unit", price: 4 },
  { id: "outlet_unit", name: "Power Outlet", type: "material", unit: "unit", price: 5 },
  { id: "toilet_unit", name: "Toilet", type: "material", unit: "unit", price: 180 },
  { id: "shower_unit", name: "Shower Set", type: "material", unit: "unit", price: 90 },
  { id: "sink_unit", name: "Sink", type: "material", unit: "unit", price: 70 },
  { id: "floor_drain", name: "Floor Drain", type: "material", unit: "unit", price: 8 },
  { id: "fence_panel", name: "Fence Material", type: "material", unit: "m", price: 40 },
  { id: "gate_unit", name: "Gate", type: "material", unit: "unit", price: 350 },
  // Labor
  { id: "worker", name: "Laborer", type: "labor", unit: "day", price: 20 },
  { id: "mason", name: "Mason", type: "labor", unit: "day", price: 28 },
  { id: "carpenter", name: "Carpenter", type: "labor", unit: "day", price: 30 },
  { id: "electrician", name: "Electrician", type: "labor", unit: "day", price: 32 },
  { id: "plumber", name: "Plumber", type: "labor", unit: "day", price: 32 },
  { id: "painter", name: "Painter", type: "labor", unit: "day", price: 26 },
  // Equipment
  { id: "concrete_mixer", name: "Concrete Mixer", type: "equipment", unit: "day", price: 25 },
];

// rule = which computed quantity feeds this item (see quantityEngine.js)
export const DEFAULT_ITEMS = [
  {
    id: "brick_wall",
    name: "Brick Wall Masonry",
    category: "architecture",
    unit: "m2",
    rule: "wallArea",
    wasteFactor: 0.05,
    resources: [
      { ref: "brick", coef: 70 },
      { ref: "cement", coef: 0.2 },
      { ref: "sand", coef: 0.04 },
      { ref: "mason", coef: 0.3 },
      { ref: "worker", coef: 0.3 },
    ],
  },
  {
    id: "plaster",
    name: "Wall Plastering",
    category: "architecture",
    unit: "m2",
    rule: "plasterArea",
    wasteFactor: 0.05,
    resources: [
      { ref: "cement", coef: 0.15 },
      { ref: "sand", coef: 0.02 },
      { ref: "mason", coef: 0.2 },
      { ref: "worker", coef: 0.2 },
    ],
  },
  {
    id: "wall_paint",
    name: "Wall Painting",
    category: "architecture",
    unit: "m2",
    rule: "paintArea",
    wasteFactor: 0.05,
    resources: [
      { ref: "paint", coef: 0.2 },
      { ref: "painter", coef: 0.1 },
      { ref: "worker", coef: 0.05 },
    ],
  },
  {
    id: "floor_tile",
    name: "Floor Tiling",
    category: "architecture",
    unit: "m2",
    rule: "floorArea",
    wasteFactor: 0.08,
    resources: [
      { ref: "ceramic_tile", coef: 1.05 },
      { ref: "cement", coef: 0.1 },
      { ref: "sand", coef: 0.03 },
      { ref: "mason", coef: 0.25 },
      { ref: "worker", coef: 0.25 },
    ],
  },
  {
    id: "ceiling",
    name: "Gypsum Ceiling",
    category: "architecture",
    unit: "m2",
    rule: "ceilingArea",
    wasteFactor: 0.05,
    resources: [
      { ref: "gypsum_board", coef: 1.05 },
      { ref: "carpenter", coef: 0.15 },
      { ref: "worker", coef: 0.15 },
    ],
  },
  {
    id: "roof",
    name: "Roof Covering",
    category: "architecture",
    unit: "m2",
    rule: "roofArea",
    wasteFactor: 0.1,
    resources: [
      { ref: "roof_tile", coef: 1.0 },
      { ref: "timber", coef: 0.02 },
      { ref: "carpenter", coef: 0.2 },
      { ref: "worker", coef: 0.2 },
    ],
  },
  {
    id: "door_install",
    name: "Door (supply & install)",
    category: "architecture",
    unit: "unit",
    rule: "doorCount",
    wasteFactor: 0,
    resources: [
      { ref: "door_leaf", coef: 1 },
      { ref: "carpenter", coef: 0.5 },
      { ref: "worker", coef: 0.5 },
    ],
  },
  {
    id: "window_install",
    name: "Window (supply & install)",
    category: "architecture",
    unit: "unit",
    rule: "windowCount",
    wasteFactor: 0,
    resources: [
      { ref: "window_unit", coef: 1 },
      { ref: "carpenter", coef: 0.4 },
      { ref: "worker", coef: 0.4 },
    ],
  },
  {
    id: "foundation",
    name: "Strip Foundation",
    category: "structure",
    unit: "m",
    rule: "foundationLength",
    wasteFactor: 0.03,
    resources: [
      { ref: "cement", coef: 2.0 },
      { ref: "sand", coef: 0.3 },
      { ref: "gravel", coef: 0.4 },
      { ref: "mason", coef: 0.5 },
      { ref: "worker", coef: 1.0 },
    ],
  },
  {
    id: "column",
    name: "RC Column",
    category: "structure",
    unit: "m3",
    rule: "columnVolume",
    wasteFactor: 0.03,
    resources: [
      { ref: "cement", coef: 8 },
      { ref: "sand", coef: 0.5 },
      { ref: "gravel", coef: 0.8 },
      { ref: "rebar", coef: 150 },
      { ref: "mason", coef: 1.5 },
      { ref: "worker", coef: 3 },
      { ref: "concrete_mixer", coef: 0.3 },
    ],
  },
  {
    id: "beam",
    name: "RC Ring Beam",
    category: "structure",
    unit: "m3",
    rule: "beamVolume",
    wasteFactor: 0.03,
    resources: [
      { ref: "cement", coef: 8 },
      { ref: "sand", coef: 0.5 },
      { ref: "gravel", coef: 0.8 },
      { ref: "rebar", coef: 120 },
      { ref: "mason", coef: 1.5 },
      { ref: "worker", coef: 3 },
    ],
  },
  {
    id: "lamp",
    name: "Lighting Point",
    category: "mep",
    unit: "unit",
    rule: "lampCount",
    wasteFactor: 0,
    resources: [
      { ref: "lamp_fixture", coef: 1 },
      { ref: "wire", coef: 8 },
      { ref: "electrician", coef: 0.3 },
      { ref: "worker", coef: 0.2 },
    ],
  },
  {
    id: "switch",
    name: "Switch Point",
    category: "mep",
    unit: "unit",
    rule: "switchCount",
    wasteFactor: 0,
    resources: [
      { ref: "switch_unit", coef: 1 },
      { ref: "wire", coef: 5 },
      { ref: "electrician", coef: 0.2 },
    ],
  },
  {
    id: "outlet",
    name: "Power Outlet Point",
    category: "mep",
    unit: "unit",
    rule: "outletCount",
    wasteFactor: 0,
    resources: [
      { ref: "outlet_unit", coef: 1 },
      { ref: "wire", coef: 6 },
      { ref: "electrician", coef: 0.25 },
    ],
  },
  {
    id: "toilet",
    name: "Toilet Fixture",
    category: "mep",
    unit: "unit",
    rule: "toiletCount",
    wasteFactor: 0,
    resources: [
      { ref: "toilet_unit", coef: 1 },
      { ref: "pipe_pvc", coef: 4 },
      { ref: "plumber", coef: 0.6 },
      { ref: "worker", coef: 0.4 },
    ],
  },
  {
    id: "shower",
    name: "Shower Fixture",
    category: "mep",
    unit: "unit",
    rule: "showerCount",
    wasteFactor: 0,
    resources: [
      { ref: "shower_unit", coef: 1 },
      { ref: "pipe_pvc", coef: 3 },
      { ref: "plumber", coef: 0.5 },
    ],
  },
  {
    id: "sink",
    name: "Sink Fixture",
    category: "mep",
    unit: "unit",
    rule: "sinkCount",
    wasteFactor: 0,
    resources: [
      { ref: "sink_unit", coef: 1 },
      { ref: "pipe_pvc", coef: 3 },
      { ref: "plumber", coef: 0.4 },
    ],
  },
  {
    id: "drain",
    name: "Floor Drain",
    category: "mep",
    unit: "unit",
    rule: "drainCount",
    wasteFactor: 0,
    resources: [
      { ref: "floor_drain", coef: 1 },
      { ref: "pipe_pvc", coef: 2 },
      { ref: "plumber", coef: 0.2 },
    ],
  },
  {
    id: "fence",
    name: "Boundary Fence",
    category: "exterior",
    unit: "m",
    rule: "fenceLength",
    wasteFactor: 0.03,
    resources: [
      { ref: "fence_panel", coef: 1 },
      { ref: "cement", coef: 0.3 },
      { ref: "sand", coef: 0.05 },
      { ref: "mason", coef: 0.2 },
      { ref: "worker", coef: 0.2 },
    ],
  },
  {
    id: "gate",
    name: "Gate",
    category: "exterior",
    unit: "unit",
    rule: "gateCount",
    wasteFactor: 0,
    resources: [
      { ref: "gate_unit", coef: 1 },
      { ref: "carpenter", coef: 0.5 },
      { ref: "worker", coef: 1 },
    ],
  },
];

export const CATEGORY_META = {
  structure: { label: "Structure", color: "#1E56A0" },
  architecture: { label: "Architecture", color: "#0D9488" },
  mep: { label: "MEP (Electrical & Plumbing)", color: "#D97706" },
  exterior: { label: "Exterior", color: "#6366F1" },
};

export const UTILITY_KINDS = [
  { id: "lamp", label: "Lamp", category: "electrical" },
  { id: "switch", label: "Switch", category: "electrical" },
  { id: "outlet", label: "Power Outlet", category: "electrical" },
  { id: "toilet", label: "Toilet", category: "plumbing" },
  { id: "shower", label: "Shower", category: "plumbing" },
  { id: "sink", label: "Sink", category: "plumbing" },
  { id: "drain", label: "Floor Drain", category: "plumbing" },
  { id: "gate", label: "Gate", category: "exterior" },
];
